### ISSUE TITLE
无法打开gui

### ISSUE THREAD

**Issue by DnoYT** [ColorsWind/VirtualMenu#3]
Task #3681 for VirtualMenu v0.0.16-dev generated an exception
java.lang.LinkageError: loader constraint violation: when resolving method "com.blzeecraft.virtualmenu.packet.packets.PacketOpenWindow.<init>(ILjava/lang/String;Lcom/blzeecraft/virtualmenu/packet/MenuType;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/blzeecraft/virtualmenu/packet/PacketManager, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/blzeecraft/virtualmenu/packet/packets/PacketOpenWindow, have different Class objects for the type com/blzeecraft/virtualmenu/packet/MenuType used in the signature
        at com.blzeecraft.virtualmenu.packet.PacketManager.lambda$0(PacketManager.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-ac735a0]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-ac735a0]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:830) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by ColorsWind** [comment]
请不要在catserver（或其他带forge）的服务器上热重载插件。
